// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/artifactregistry/v1beta2/repository.proto

package com.google.devtools.artifactregistry.v1beta2;

public interface DeleteRepositoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.artifactregistry.v1beta2.DeleteRepositoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the repository to delete.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the repository to delete.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
