// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/artifactregistry/v1beta2/tag.proto

package com.google.devtools.artifactregistry.v1beta2;

public interface TagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.artifactregistry.v1beta2.Tag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the tag, for example:
   * "projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/tags/tag1".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the tag, for example:
   * "projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/tags/tag1".
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The name of the version the tag refers to, for example:
   * "projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/versions/sha256:5243811"
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * The name of the version the tag refers to, for example:
   * "projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/versions/sha256:5243811"
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
